---
- hosts: all

  tasks:
  - name: Set authorized key
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/home/hxiang/.ssh/id_rsa.pub') }}"

  - name: Install benchmark tools
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - sysbench

  - name: Install speedtest-cli
    get_url:
      url: https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
      dest: ~/
      mode: 0755

  - name: Download database IO test lua
    get_url:
      url: https://github.com/akopytov/sysbench/raw/master/src/lua/oltp_read_write.lua
      dest: ~/

  - name: Install application dependencies packages
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - python34
      - python34-devel
      - python34-setuptools
      - python34-pip
      - git
      - virtualenv

  - name: Run benchmark
    command: echo 'hello world'

